# .goreleaser.yml
project_name: enterprise-proxy-software

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}
      - -X main.BuiltBy=goreleaser

dist: ./dist/outputs/dist

upx:
  - enabled: true
    # Filter by build ID(s) to compress. Leave empty to allow all builds.
    ids:
      - remembrances-mcp
    # Only compress linux amd64/arm64 by default
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    compress: '1'
    lzma: true
    brute: false

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: madeindigio
    name: enterprise-proxy-software
  draft: true
