version: 2
# .goreleaser.yml
project_name: enterprise-proxy-software

before:
  hooks:
    - go mod tidy

builds:
  - id: enterprise-proxy-software
    main: ./src/main.go
    binary: enterprise-proxy-software
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - "386"
      - "amd64"
      - "arm"
      - "arm64"
    goarm:
      - "7"
    ldflags:
      - "-s"
      - "-w"
      - "-X github.com/madeindigio/enterprise-proxy-software/pkg/version.CommitHash={{.Commit}}"
      - "-X github.com/madeindigio/enterprise-proxy-software/pkg/version.Version={{.Version}}"
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: "386"
      - goos: windows
        goarch: "arm"
      - goos: windows
        goarch: "arm64"

dist: ./dist/release

upx:
  - enabled: true
    # Filter by build ID(s) to compress. Leave empty to allow all builds.
    ids:
      - enterprise-proxy-software
    # Only compress linux amd64/arm64 by default
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    compress: '1'
    lzma: true
    brute: false
    
archives:
  - id: bin
    formats: ['binary']
  - id: tar
    formats: ['tar.gz']


changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: madeindigio
    name: enterprise-proxy-software
  draft: true
